### ISSUE TITLE
400 Error

### ISSUE THREAD

**Issue by paga2004** [abertschi/postcard_creator_wrapper#13]
Hello abertschi

I was really surprised that this fantastic API exists when I found it. I immediately had thousands of ideas about what to do with it.  Unfourtenetley I got this annoying error every time I try it. **(postcard_creator.postcard_creator.PostcardCreatorException: error in request put https://postcardcreator.post.ch/rest/2.2/users/503438/mailings/45985710/pages/2. status_code: 400)**
Is this a known issue or am I doing something wrong? 

Thanks for your reply.

**Comment by abertschi** [comment]
400 indicates that there is an issue with your submitted text.

see:
https://github.com/abertschi/postcards/issues/25

**Comment by paga2004** [comment]
OMG, it worked!! :D 
Thank you very much for the quick and helpful reply.
