### ISSUE TITLE
Valid Credicals

### ISSUE THREAD

**Issue by aaronmeier10** [abertschi/postcard_creator_wrapper#19]
if i run this code on the new wrapper:

```
from postcard_creator.postcard_creator import PostcardCreator, Postcard, Token, Recipient, Sender
import datetime

email = 'aaron.uferweg@gmail.com'
pw = '********'
token = Token()
token.fetch_token(username=email, password=pw,method='legacy')
token.has_valid_credentials(username=email, password=pw,method='legacy')

w = PostcardCreator(token)
print(w.has_free_postcard())
```
it throws this error:

```
ERROR:root:Username/password authentication failed. Are your credentials valid?.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/postcard_creator/token.py", line 120, in fetch_token
    raise PostcardCreatorException()
postcard_creator.postcard_creator.PostcardCreatorException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "status.py", line 12, in <module>
    token.fetch_token(username=email, password=pw,method='legacy')
  File "/usr/local/lib/python3.7/dist-packages/postcard_creator/token.py", line 133, in fetch_token
    raise e
postcard_creator.postcard_creator.PostcardCreatorException: Could not get access_token. Something broke. set increase debug verbosity to debug why

```
bevore version v1.1 it worked well with this code. Now I added the `method='legacy'` parameter to the `token.fetch_token` and `token.has_valid_credentials` as it is documented.

Any help?

**Comment by abertschi** [comment]
To make this clear, you can verify that the issue does not occur if you run a version below 1.1? If so, which version?

**Comment by aaronmeier10** [comment]
I can't replicate the running version, but i am shure it was Version 0.0.8.
But is the Code i posted not the right way to do it in the newest version?

**Comment by abertschi** [comment]
Your error indicates an issue with your account. There are two possible scenarios.
- Your account has an issue, as indicated in the error.
- And endpoint broke and the framework has an issue.

I think the former one is a lot more likely as i do not have other reports claiming issues with the framework.

Are you sure your credentials are valid? You may try to login on the official site with your credentials.
The vendor is not forcing many accounts to the new swissId authentication.

**Comment by abertschi** [comment]
Closing this, feel free to reopen if issue persists
