### ISSUE TITLE
Renew expired token causes an error

### ISSUE THREAD

**Issue by wp99cp** [abertschi/postcard_creator_wrapper#24]
Why does the following code always give an error message? In other words, how is it possible to refresh an expired token?

```python
import time
from postcard_creator.postcard_creator import Token

token = Token()
token.fetch_token(username='...', password='...', method='swissid')
print(token.headers)

time.sleep(token.token_expires_in)  # wait until token expires

token = Token()  # the program also crashes, if you leave out this line of code
token.fetch_token(username='...', password='...', method='swissid')
print(token.headers)
```

I think the problem is caused by the following request. The second time we post our credentials we got a 403 as a response. And the problem must be in the postcard_creator_wrapper code since if you just rerun the entire program the authentication succeeds.
https://github.com/abertschi/postcard_creator_wrapper/blob/276f099b1633b5c9147ea2ce61d1fbe911dbc780/postcard_creator/token.py#L263-L272

Instead of creating a new token object every time, it would be nice to have a method refetch_token, that clears the local vars, e.g., success and fetches a new token. **Usecase:** First, you check when the next postcard can be sent. Then the program waits until a timer expires, refreshes the access token and send the postcard.

**Comment by abertschi** [comment]
> The second time we post our credentials we got a 403 as a response.

Please be more verbose. What is the exact response?

A method to refetch is optional, you can just fetch a new token after some time. Why the above code fails is unclear, however, and must be further investigated.

**Comment by abertschi** [comment]
In order to call fetch again without instantiating a new token, the initialization code in the constructor must be recalled.

**Comment by wp99cp** [comment]
Did you run the programme above?
For me, it crashes in both cases, with and without the initialization code being run again. Even if you create an entirely new object (see code below).

```python
import time
from postcard_creator.postcard_creator import Token

token = Token()
token.fetch_token(username='...', password='...', method='swissid')
print(token.headers)

time.sleep(token.token_expires_in)  # wait until token expires

token2 = Token()  # new token object
token2.fetch_token(username='...', password='...', method='swissid')
print(token2.headers)
```

The error I got is the one bellow. Caused by the 403 error of the post request 271.

```
Traceback (most recent call last):
  File "D:\Projekte\postCardCreator\postcard_creator\token.py", line 283, in _get_access_token_swissid
    url = resp.json()['nextAction']['successUrl']
  File "D:\Projekte\postCardCreator\venv\lib\site-packages\requests\models.py", line 891, in json
    return complexjson.loads(
  File "C:\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

Please enlighten me if I am doing something completely wrong.

**Comment by abertschi** [comment]
Thanks for more detail. Yes I did run a sample snippet but it turned out my code was using the legacy wrapper.
Ok, this is a legitimate bug. Will flag it as such. I am currently still busy with grad school exams but I can (hopefully) look into it next week. You can increase the login verbosity such that request and responses are traced and investigate the problem in the meantime. Otherwise I will see if I find some time next week :+1:
