### ISSUE TITLE
Newlines

### ISSUE THREAD

**Issue by maede97** [abertschi/postcard_creator_wrapper#35]
First of all: thanks for this awesome tool! Works like a charm!

My question is about new-lines

Like one way would be entering python text like this:
`message = "First Line\n Second Line`

or even, with the triple ":
```
message = """First Line
Second Line"""
```
Is there a way that this wrapper supports this?
Because newlines are (in my case) just ignored by this tool (https://github.com/abertschi/postcard_creator_wrapper/blob/master/postcard_creator/postcard_img_util.py#L126)

**Comment by abertschi** [comment]
thanks for shouting out. hmm, you are right, newlines are indeed dropped. off the top of my head there are the following things you could do (none of them are supported as is):
- in your project, overwrite https://github.com/abertschi/postcard_creator_wrapper/blob/c09f07f00d04689c17a56b69341aa657b8673d6f/postcard_creator/postcard_creator_swissid.py#L149 with your own formatting logic to create a cover
- we can adapt https://github.com/abertschi/postcard_creator_wrapper/blob/c09f07f00d04689c17a56b69341aa657b8673d6f/postcard_creator/postcard_img_util.py#L76 such that the size search does consider newlines in the input text.
- the last time when I looked at this, the endpoint supported a plain/txt field for the message. the old endpoints only used this field and one could not upload a pixel cover for text.
https://github.com/abertschi/postcard_creator_wrapper/blob/c09f07f00d04689c17a56b69341aa657b8673d6f/postcard_creator/postcard_creator_swissid.py#L124 If you dont want text formatting you could submit your text to that field which perhaps supports newlines (afaik the old endpoint did support newlines).


I may look into this too, but as of right now I am busy with other things. :)

**Comment by maede97** [comment]
https://github.com/maede97/postcard_creator_wrapper/commit/230704f59848955537b6fd1dbdde5fcaade557f4

I think I fixed it :-)
Maybe you can have a short look at it (my use-case seemed to work fine).
If you want, I can create a PR. Just ping me :-)
