### ISSUE TITLE
authentication not working

### ISSUE THREAD

**Issue by richi0** [abertschi/postcard_creator_wrapper#37]
It looks like authentication is not working for me. I use swissid and I checked on post.ch and the app that my login is correct.

My code
```
from postcard_creator.postcard_creator import (
    Token,
)

token = Token()
token.fetch_token(username="myemail", password="mypw", method="swissid")
```

The Error
```
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    token.fetch_token(username="myemail", password="mypw", method="swissid")
  File "/home/r/python/postcard/.venv/lib/python3.8/site-packages/postcard_creator/token.py", line 128, in fetch_token
    raise e
  File "/home/r/python/postcard/.venv/lib/python3.8/site-packages/postcard_creator/token.py", line 122, in fetch_token
    access_token = self._get_access_token_swissid(session, username, password)
  File "/home/r/python/postcard/.venv/lib/python3.8/site-packages/postcard_creator/token.py", line 340, in _get_access_token_swissid
    url = step7_soup.find('form', {'name': 'LoginForm'})['action']
TypeError: 'NoneType' object is not subscriptable
```

Did post change the API?
BTW I found this project because I wanted to do the exact same. Good job!

**Comment by abertschi** [comment]
> Did post change the API?

Not that I am aware of. I just checked swissid based authentication. It worked just fine.

Here are some ideas you can follow up:
- Make sure you use the latest version
- Increase debugging verbosity to trace issue
- 2 factor authentication is not supported. Disable it.

Cheers.

**Comment by richi0** [comment]
Thanks for your fast response. I logged into the Postcard Creator app again. This time it asked me to add my address to swissid. After doing that everything worked.
