### ISSUE TITLE
postcard_creator.postcard_creator.PostcardCreatorException: fail to fetch https://account.post.ch/idp/

### ISSUE THREAD

**Issue by elievischel** [abertschi/postcard_creator_wrapper#46]
I have just followed the example to send a postcard, however I get a response of 

postcard_creator.postcard_creator.PostcardCreatorException: fail to fetch https://account.post.ch/idp/?login&targetURL=https://pccweb.api.post.ch/SAML/ServiceProvider/?redirect_uri=ch.post.pcc://auth/XXXXXXXXXXXXXXXXXXX&profile=default&app=pccwebapi&inMobileApp=true&layoutType=standard

Any help would be great, 
Best regards,

**Comment by abertschi** [comment]
just verified the endpoints. they work just fine. Can you precisely describe what you did to get stuck?
